[package]
name = "reserver"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
sqlx = { version = "0.8", features = ["postgres", "runtime-tokio-native-tls", "chrono"] }
chrono = "0.4"
thiserror = "1.0"
